name: docs

on:
  workflow_call:
    inputs:
      ubuntu_deps:
        description: 'Ubuntu packages to be installed'
        required: false
        type: string
        default: ""
      pip_deps:
        description: 'PIP dependencies to be installed'
        required: false
        type: string
        default: ""

jobs:
  build_sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Update ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install crudini

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Update pip/wheel infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Ubuntu dependencies
        run: |
          [ ! -z "${{ inputs.ubuntu_deps }}" ] && sudo apt-get install "${{ inputs.ubuntu_deps }}"

      - name: Install additional pip dependencies
        run: |
          [ ! -z "${{ inputs.pip_deps }}" ] && sudo apt-get install "${{ inputs.pip_deps }}"

      - name: Build and install
        run: pip install -v .

      - name: Install documenteer
        run: pip install 'documenteer[pipelines]<0.7'

      - name: Build documentation
        working-directory: ./doc
        run: package-docs build
