name: docs

on:
  workflow_call:

jobs:
  build_sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Update ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install crudini

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Update pip/wheel infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Install graphviz
        run: sudo apt-get install graphviz

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Ubuntu dependencies
        run: |
          if [ -e build_docs.ini ]
          then
            pkg=$(crudini --get build_docs.ini ubuntu install 2>/dev/null) && \
              sudo apt-get install ${pkg} || true
          fi

      - name: Install additional pip dependencies
        run: |
          if [ -e build_docs.ini ]
          then
            pkg=$(crudini --get build_docs.ini pip install 2>/dev/null) && \
              pip install ${pkg} || true
          fi

      - name: Build and install
        run: pip install -v .

      - name: Install documenteer
        run: pip install 'documenteer[pipelines]<1.0'

      - name: Build documentation
        working-directory: ./doc
        run: package-docs build
