name: cmake

on:
  workflow_call:
    inputs:
      ubuntu_deps:
        description: 'Ubuntu packages to be installed'
        required: false
        type: string
        default: ""
      pip_deps:
        description: 'PIP dependencies to be installed'
        required: false
        type: string
        default: ""

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Update ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install crudini

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python prereqs
        run: |
          pip install \
            pytest \
            pytest-flake8

      - name: Install Ubuntu dependencies
        if: ${{ inputs.ubuntu_deps != '' }}
        run: sudo apt-get install "${{ inputs.ubuntu_deps }}"

      - name: Install additional pip dependencies
        if: ${{ inputs.pip_deps != '' }}
        run: sudo apt-get install "${{ inputs.pip_deps }}"

      - name: CMake configure
        run: |
          cmake \
            -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install \
            -B ${{github.workspace}}/build

      - name: CMake build
        run: cmake --build ${{github.workspace}}/build --parallel `nproc`

      - name: CMake test
        working-directory: ${{github.workspace}}/build
        run: ctest

      - name: CMake install
        run: cmake --build ${{github.workspace}}/build --target install

      - name: Python tests
        env:
          PYTHONPATH: ${{github.workspace}}/build/install/python
          LD_LIBRARY_PATH: ${{github.workspace}}/build/install/lib
        run: pytest -r a -v
