name: lint docstrings

on:
  workflow_call:
    inputs:
      args:
        description: 'Arguments passed to docstyle'
        type: string
        required: true

jobs:
  docstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: pip install pydocstyle tomli

      - name: Run docstyle with parameters ${{ inputs.args }}
        run: pydocstyle  ${{ inputs.args }}
