name: formatting

on:
  workflow_call:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install isort and black
        run: pip install isort black

      - name: Run isort
        run: |
          isort --df --check-only \
               $(test -e bin.src/ && echo 'bin.src/') \
               $(test -e python/ && echo 'python/') \
               $(test -e tests/ && echo 'tests/')

      - name: Run black
        run: |
          black --check --verbose --diff \
               $(test -e bin.src/ && echo 'bin.src/*') \
               $(test -e python/ && echo 'python/') \
               $(test -e tests/ && echo 'tests/')
