name: formatting and linting checks

on:
  workflow_call:

jobs:
  check-tooling:
    outputs:
      use_ruff_format: ${{ steps.tooling.outputs.use_ruff_format }}
      use_ruff_check: ${{ steps.tooling.outputs.use_ruff_check }}
      use_isort: ${{ steps.tooling.outputs.use_isort }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check which tooling to use
        id: tooling
        run: |
          # Decide to run ruff check if there is a ruff format configuration.
          use_ruff_format="false"
          use_ruff_check="false"
          use_isort="true"
          if [ -e pyproject.toml ]; then
            if [ ! -z $(grep tool.ruff.format pyproject.toml) ]; then
              use_ruff_format="true"
            fi
            if [ ! -z $(grep tool.ruff.lint pyproject.toml) ]; then
              use_ruff_check="true"
            fi
            # No need to run isort if ruff check is already doing it.
            if [ ! -z $(grep tool.ruff.lint.isort pyproject.toml) ]; then
              use_isort="false"
              use_ruff_check="true"
            fi
          fi
          if [ "${use_ruff_format}" == "true" ]; then
            echo "Using ruff format"
            echo "use_ruff_format=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Using black for formatting"
            echo "use_ruff_format=false" >> "${GITHUB_OUTPUT}"
          fi
          if [ "${use_ruff_check}" == "true" ]; then
            echo "Using ruff check for linting"
            echo "use_ruff_check=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Using flake8 for linting"
            echo "use_ruff_check=false" >> "${GITHUB_OUTPUT}"
          fi
          if [ "${use_isort}" == "true" ]; then
            echo "Using isort tool"
            echo "use_isort=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Using ruff check for isort"
          fi
  format_with_ruff:
    needs: [check-tooling]
    runs-on: ubuntu-latest
    if: "${{ needs.check-tooling.outputs.use_ruff_format == 'true' }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv pip install --system ruff
      - name: Run Ruff format
        run: ruff format --check --diff .
  format_with_black:
    needs: [check-tooling]
    runs-on: ubuntu-latest
    if: "${{ needs.check-tooling.outputs.use_ruff_format == 'false' }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv pip install --system black
      - name: Run black format
        run: |
          black --check --verbose --diff \
            $(test -e bin.src/ && echo 'bin.src/*') \
            $(test -e python/ && echo 'python/') \
            $(test -e tests/ && echo 'tests/')
  lint_with_ruff:
    needs: [check-tooling]
    runs-on: ubuntu-latest
    if: "${{ needs.check-tooling.outputs.use_ruff_check == 'true' }}"
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  lint_with_flake8:
    needs: [check-tooling]
    runs-on: ubuntu-latest
    if: "${{ needs.check-tooling.outputs.use_ruff_check == 'false' }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install flake8
        run: |
          python -m pip install uv
          uv pip install --system flake8==7.1 flake8-github-annotations

      - name: Run linter
        run: flake8 --format github
  isort:
    needs: [check-tooling]
    runs-on: ubuntu-latest
    if: "${{ needs.check-tooling.outputs.use_isort == 'true' }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install isort
        run: |
          pip install uv
          uv pip install --system isort

      - name: Check package sorting
        run: |
          isort --df --check-only \
               $(test -e bin.src/ && echo 'bin.src/') \
               $(test -e python/ && echo 'python/') \
               $(test -e tests/ && echo 'tests/')
