name: formatting

on:
  workflow_call:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install isort and black
        run: pip install isort black

      - name: Run isort
        run: |
          isort --check-only \
               $([ -e bin.src/ ] && echo 'bin.src/') \
               $([ -e python/ ] && echo 'python/') \
               $([ -e tests/ ] && echo 'tests/')

      - name: Run black
        run: |
          black --check --verbose --diff \
               $([ test -e bin.src/ ] && echo 'bin.src/*') \
               $([ test -e python/ ] && echo 'python/') \
               $([ $(test -e tests/ ] && echo 'tests/')
