name: formatting

on:
  workflow_call:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install isort and black
        run: |
          pip install uv
          uv pip install --system isort black ruff

      - name: Check package sorting
        run: |
          isort --df --check-only \
               $(test -e bin.src/ && echo 'bin.src/') \
               $(test -e python/ && echo 'python/') \
               $(test -e tests/ && echo 'tests/')

      - name: Check formatting
        run: |
          # Decide to run ruff check if there is a ruff format configuration.
          use_ruff=""
          if [ -e pyproject.toml ]; then
              if [ ! -z $(grep tool.ruff.format pyproject.toml) ]; then
                 use_ruff="yes"
              fi
          fi
          if [ -z ${use_ruff} ]; then
            echo Running black
            black --check --verbose --diff \
               $(test -e bin.src/ && echo 'bin.src/*') \
               $(test -e python/ && echo 'python/') \
               $(test -e tests/ && echo 'tests/')
          else
            echo Running ruff format
            ruff format --check --diff
          fi
