name: lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install
        run: pip install flake8==7.3.0 flake8-github-annotations

      - name: Run linter
        run: flake8 --format github
