name: Lint Markdown Files

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Run linter
        uses: actionshub/markdownlint@main
