name: Run mypy

on:
  workflow_call:
    inputs:
      mypy_package:
        description: "The name and version number of the mypy package that will be passed to pip.  Example: mypy==1.9.0"
        default: mypy
        required: false
        type: string
      folders:
        description: "List of folders to check, by default only python/ is checked.  Example: \"python test\""
        default: "python"
        required: false
        type: string

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install
        run: |
          pip install uv
          uv pip install --system '${{ inputs.mypy_package }}' pydantic lsst-versions

      - name: Install types dependencies
        run: |
          if [ -e types.txt ]
          then
            uv pip install --system -r types.txt
          fi
      - name: Install lsst dependencies
        run: |
          if [ -e requirements.txt ]
          then
            uv pip install --system -r requirements.txt
          fi

      - name: Run mypy
        run: |
          lsst-version . --write-version
          mypy ${{ inputs.folders }}
