name: Run mypy

on:
  workflow_call:

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install
        run: pip install mypy pydantic

      - name: Install types dependencies
        run: |
          if [ -e types.txt ]
          then 
            pip install -r types.txt
          fi
      - name: Install lsst dependencies
        run: |
          if [ -e requirements.txt ]
          then
             pip install -r requirements.txt
          fi

      - name: Fake a version
        run: |
          prefix="python/lsst"
          if [ ! -e ${prefix} ]
          then
            prefix="python"
          fi  
          repo=${{ github.event.repository.name }}
          if [ ! -e "${prefix}/${repo}" ]
          then
            repo=$(echo "${repo}" | sed 's/_/\//g')
          fi
          echo "__all__ = ['__version__']" > "${prefix}/${repo}/version.py"
          echo "__version__ = '0.0.1'" >> "${prefix}/${repo}/version.py"

      - name: Change to source directory and run mypy
        run: mypy "${prefix}"
