name: "Check that the 'main' branch was not merged into the development branch"
on:
  workflow_call:

jobs:
  rebase-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Check that 'main' or backport branch 'vX.Y.x' are not merged into the development branch
        env:
            GH_TOKEN: ${{ github.token }}
            PR_NUMBER: ${{ github.event.pull_request.number }}
            REPO: ${{ github.repository }}
        run: |
            bad_commits="$(
              gh api "repos/${REPO}/pulls/${PR_NUMBER}/commits" --paginate \
                --jq '.[] | select(.commit.message | test("^Merge branch '\''(main|v\\d+\\.\\d+\\.x)'\''")) | .sha + " " + (.commit.message | split("\n")[0])'
            )"

            if [ -n "$bad_commits" ]; then
              echo "::error::Merge commits detected:"
              echo "$bad_commits"
              echo ""
              echo "This step failed because you merged the 'main' or release backport branch 'vX.Y.x' into the development branch,"
              echo "likely by clicking the 'Update branch' button on the GitHub pull request page."
              echo ""
              echo "To fix this, update the 'main' or backport branch locally and rebase against it:"
              echo "  git fetch origin"
              echo "  git rebase origin/main"
              echo ""
              echo "See https://developer.lsst.io/work/flow.html#pushing-code for detailed instructions."
              echo "To avoid this in the future, use 'Update with rebase' from the dropdown next to the Update branch button."
              exit 1
            fi
