name: "Check that the 'main' branch was not merged into the development branch"
on:
  workflow_call:

jobs:
  rebase-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Check that 'main' or backport branch 'vX.Y.x' are not merged into the development branch
        env:
            GH_TOKEN: ${{ github.token }}
            PR_NUMBER: ${{ github.event.pull_request.number }}
            REPO: ${{ github.repository }}
        run: |
            bad_commits="$(
              gh api "repos/${REPO}/pulls/${PR_NUMBER}/commits" --paginate \
                --jq '.[] | select(.commit.message | test("^Merge branch '\''(main|v[0-9]+\\.[0-9]+\\.x)'\''")) | .sha + " " + (.commit.message | split("\n")[0])'
            )"

            if [ -n "$bad_commits" ]; then
              echo "$bad_commits"
              echo "This step failed because you merged the 'main' or release backport branch 'vX.Y.x' into the development branch."
              echo "Please rebase against the latest 'main' or backport branch instead."
              exit 1
            fi
