---
name: Commitlint

"on":
  workflow_call:
    inputs:
      lint-commits:
        description: >-
          Lint commit messages in current branch or PR according to conventional-commit
          or custom rules (see `custom-rules` input).
        type: boolean
        required: false
        default: false
      rebase-checker:
        description: >-
          Check for merge commits of main or master into this branch, encouraging rebase behavior instead.
        type: boolean
        required: false
        default: true
      do-not-merge-checker:
        description: >-
          Check for explicit "DO NOT MERGE" commit messages
        type: boolean
        required: false
        default: true
      dependency-checker:
        description: >-
          Check `requirements`-style dependencies that refer to ticket branches.
        type: boolean
        required: false
        default: true
      custom-rules:
        description: >-
          Custom rules module to use with lint-commits
          (relative path to file in calling repository, e.g., `.github/config.ts`)
        type: string
        required: false
        default: ""
      verbose:
        description: Whether to run `commitlint` commands with the `--verbose` flag.
        type: boolean
        required: false
        default: false
      workflow-repo:
        description: >-
          The name of the workflow repository (i.e., the repository hosting
          this workflow and its tooling).
        type: string
        required: false
        default: "lsst/rubin_workflows"
      workflow-ref:
        description: >-
          The branch name in the workflow repository from which the tooling
          should be used.
        type: string
        required: false
        default: "main"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0

      - name: Checkout workflow repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          repository: ${{ inputs.workflow-repo}}
          ref: ${{ inputs.workflow-ref }}
          path: .wf
          sparse-checkout: |
            .github/commitlint

      - name: Set workflow variables
        run: |
          WF_PATH=.wf/.github/commitlint
          echo "WF_PATH=${WF_PATH}" >> $GITHUB_ENV
          if [[ -n '${{ inputs.custom-rules }}' ]]
          then
            CUSTOM_RULES='${{ inputs.custom-rules }}'
            EXT="${CUSTOM_RULES##*.}"
            cp "${GITHUB_WORKSPACE}/${CUSTOM_RULES}" "${WF_PATH}/custom-rules.${EXT}"
            echo "COMMITLINT_CONFIG=--extends=./${WF_PATH}/custom-rules.${EXT}" >> $GITHUB_ENV
          else
            echo "COMMITLINT_CONFIG=--default-config" >> $GITHUB_ENV
          fi

          if [[ '${{ inputs.verbose }}' = 'true' ]]
          then
            echo "VERBOSE=--verbose" >> $GITHUB_ENV
          else
            echo "VERBOSE=" >> $GITHUB_ENV
          fi

      - name: Determine commit range
        id: commits
        run: |
          if [[ '${{ github.event_name }}' == "pull_request" ]]; then
            HEAD='${{ github.event.pull_request.head.sha }}'
            BASE='${{ github.event.pull_request.base.sha }}'
          elif [[ '${{ github.event_name }}' == "push" ]]; then
            MAIN='origin/${{ github.event.repository.default_branch }}'
            BRANCH='${{ github.ref_name }}'
            HEAD='${{ github.event.after }}'
            BASE="$(git log "${MAIN}".."${BRANCH}" --oneline --format=%H | tail -1)"
          fi
          echo "base=${BASE}" >> $GITHUB_OUTPUT
          echo "head=${HEAD}" >> $GITHUB_OUTPUT

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6  # v2.2.0
        with:
          bun-version: 1.3.14

      - name: Install commitlint
        working-directory: ${{ env.WF_PATH }}
        run: >
          bun install --production --frozen-lockfile --no-save

      - name: Rebase Checker (PR Branch must be rebased, not merged into)
        if: inputs.rebase-checker
        working-directory: ${{ env.WF_PATH }}
        run: >
          bunx --no-install --bun
          commitlint
          --config "${WF_PATH}/commitlint-rebase-checker.config.mjs"
          --from '${{ steps.commits.outputs.base }}' --to '${{ steps.commits.outputs.head }}'
          --cwd "${GITHUB_WORKSPACE}" "${VERBOSE}"

      - name: Do Not Merge Checker
        if: inputs.do-not-merge-checker
        working-directory: ${{ env.WF_PATH }}
        run: >
          bunx --no-install --bun
          commitlint
          --config "${WF_PATH}/commitlint-do-not-merge.config.mjs"
          --from '${{ steps.commits.outputs.base }}' --to '${{ steps.commits.outputs.head }}'
          --cwd "${GITHUB_WORKSPACE}" "${VERBOSE}"

      - name: Validate Commits as Conventional Commits
        if: inputs.lint-commits
        working-directory: ${{ env.WF_PATH }}
        run: >
          bunx --no-install --bun
          commitlint
          "${COMMITLINT_CONFIG}"
          --from '${{ steps.commits.outputs.base }}' --to '${{ steps.commits.outputs.head }}'
          --cwd "${GITHUB_WORKSPACE}" "${VERBOSE}"

  dependency-checker:
    if: inputs.dependency-checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0

      # This is a rough approach to the problem and doesn't necessarily work
      # with uv-based projects because it's perfectly valid to find a false
      # positive match in a `[tool.*]` configuration in pyproject.toml.
      # It also won't identify dependencies that are pinned to a commit hash
      # instead of a branch name (as with `uv export`), or where the ticket
      # branch has been URL-encoded (as with `uv.lock`).
      - name: Check Dependencies for Development Branches
        shell: bash
        run: |
          DEPFILES=(requirements.txt requirements/main.in requirements/test.in)
          MATCH="tickets/DM-"
          for f in "${DEPFILES[@]}"
          do
           if $( test -f $f && grep -q "$MATCH" "$f" )
           then
            echo "Ticket branches found in $f:"
            grep -n "$MATCH" "$f"
            exit 1
           fi
          done

  rebase_checker:
    needs:
      - commitlint
      - dependency-checker
    runs-on: ubuntu-latest
    steps:
      - name: Rebase Checker Passed
        run: echo "Commit and dependency hygiene tests passed"
    